name: EndgameMaster

options:
  bundleIdPrefix: com.codevynix

targets:
  EndgameMaster:
    type: application
    platform: iOS
    deploymentTarget: "15.0"

    sources:
      - path: .
        excludes:
          - .git
          - .github
          - build

      - path: Stockfish/src

    resources:
      - Resources

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.codevynix.endgamemaster
        SWIFT_OBJC_BRIDGING_HEADER: EndgameMaster-Bridging-Header.h
        ENABLE_BITCODE: NO
