settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.codevynix.endgamemaster
    INFOPLIST_FILE: Info.plist
    SWIFT_VERSION: 5.0
    
    OTHER_LDFLAGS:
      - -lc++
    
    HEADER_SEARCH_PATHS:
      - Engine