name: Build Stockfish for macOS

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Install dependencies
        run: brew install make gcc

      - name: Clone Stockfish
        run: git clone https://github.com/official-stockfish/Stockfish.git

      - name: Build Stockfish
        run: |
          cd Stockfish/src
          make build ARCH=x86-64-modern

      - name: Copy binary
        run: |
          mkdir -p Resources
          cp Stockfish/src/stockfish Resources/stockfish
          chmod +x Resources/stockfish

      - name: Commit and push binary
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add Resources/stockfish
          git commit -m "Add Stockfish binary" || echo "No changes"
          git push