name: iOS IPA Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app

      - name: Install XcodeGen
        run: brew install xcodegen

      - name: Build Stockfish
        run: |
           git clone https://github.com/official-stockfish/Stockfish.git

      - name: Generate project
        run: xcodegen generate

      - name: Archive app
        run: |
          xcodebuild \
            -project EndgameMaster.xcodeproj \
            -scheme EndgameMaster \
            -configuration Release \
            -destination 'generic/platform=iOS' \
            -archivePath build/EndgameMaster.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            archive

      - name: Create IPA (clean bundle only)
        run: |
          mkdir -p Payload

          APP_PATH="build/EndgameMaster.xcarchive/Products/Applications/EndgameMaster.app"

          echo "Using app at: $APP_PATH"

          cp -R "$APP_PATH" Payload/

          zip -r EndgameMaster.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: EndgameMaster.ipa
          path: EndgameMaster.ipa
